### ISSUE TITLE
Upgrade ELK to latest versions

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-analytic#28]
Currently, Elasticsearch is 2.4, Kibana is 4.5 and logstash is 2.3

**Comment by infosec-alchemist** [comment]
Try and use the base images as much as absolutely possible.  The only problem is with plugin installations.

**Comment by MikeKemmerer** [comment]
The beats config I'm working on for windows event logs and sysmon will be 5.0.x compliant. It will also include mappings.

**Comment by infosec-alchemist** [comment]
Oh good.  I was probably going to check out beats.  I am hoping it makes deployment more cohesive.  And I didn't like some things with NXLog.
