### ISSUE TITLE
Investigate Beats

### ISSUE THREAD

**Issue by infosec-alchemist** [iadgov/unfetter-analytic#3]
Look at Beats and investigate if we should move to it and away from NXlog

**Comment by MikeKemmerer** [comment]
I've got a beats-based filter for sysmon and windows logs in test right now our project. Did you want to have separate configuration files or have it inspect the tags to determine whether to process it as nxlog or sysmon?

**Comment by infosec-alchemist** [comment]
I was wondering if we could ditch NXLog completely for BEATS.  I don't like how nxlog changes some values in the shipped event log in an attempt to make things similar across source types.

How have you found BEATS?  Does it integrate better?  Are there good TLS options so the traversing data is encrypted?
